site_name: AegisMC
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: deep purple
  logo: assets/logo.png
  favicon: assets/icon.png
  features:
    - navigation.tabs
    - navigation.instant
    - header.autohide
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/aegismctwt
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/rssB8hPbKN
    - icon: fontawesome/brands/github
      link: https://github.com/CobaltDevel/aegismc
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences